### PR TITLE
naive: add support for feature switches

### LINKED ISSUE #641: PostQuantumKyber breaks middleboxes after v124
Hi
After updating both server and client to the [v124](https://github.com/klzgrad/naiveproxy/releases/tag/v124.0.6367.54-2); i have problem with client, it does not work anymore (both socks and redir mode). but with v123 everything is normal and working.
```
root@client:/opt/naiveproxy# ./naive config.json

[0427/085057.622121:INFO:naive_proxy_bin.cc(498)] Proxying via HTTPS server.com:443
[0427/085057.758080:INFO:naive_proxy_bin.cc(698)] Listening on socks://0.0.0.0:1080
[0427/085103.827213:INFO:naive_connection.cc(273)] Connection 1 to api.github.com:443
[0427/085103.834976:INFO:naive_connection.cc(273)] Connection 2 to collector.github.com:443
[0427/085104.125668:INFO:naive_connection.cc(273)] Connection 3 to api.github.com:443
[0427/085104.163995:INFO:naive_connection.cc(273)] Connection 4 to alive.github.com:443
[0427/085105.185023:INFO:naive_connection.cc(273)] Connection 5 to api.github.com:443
[0427/085105.252068:INFO:naive_connection.cc(273)] Connection 6 to collector.github.com:443
[0427/085107.080554:INFO:naive_connection.cc(273)] Connection 7 to witch.valdikss.org.ru:80
[0427/085134.121821:INFO:naive_proxy.cc(184)] Connection 5 closed: ERR_PROXY_CONNECTION_FAILED
[0427/085134.122036:INFO:naive_proxy.cc(184)] Connection 6 closed: ERR_PROXY_CONNECTION_FAILED
[0427/085134.133097:INFO:naive_connection.cc(273)] Connection 8 to api.github.com:443
[0427/085134.134542:INFO:naive_connection.cc(273)] Connection 9 to collector.github.com:443
[0427/085134.246392:INFO:naive_proxy.cc(184)] Connection 9 closed: ERR_PROXY_CONNECTION_FAILED
[0427/085134.253462:INFO:naive_proxy.cc(184)] Connection 8 closed: ERR_PROXY_CONNECTION_FAILED
[0427/085134.343275:INFO:naive_proxy.cc(184)] Connection 4 closed: ERR_PROXY_CONNECTION_FAILED
[0427/085135.358480:INFO:naive_proxy.cc(184)] Connection 3 closed: ERR_PROXY_CONNECTION_FAILED
[0427/085135.430652:INFO:naive_proxy.cc(184)] Connection 2 closed: ERR_PROXY_CONNECTION_FAILED
[0427/085137.507773:INFO:naive_proxy.cc(184)] Connection 7 closed: ERR_PROXY_CONNECTION_FAILED
[0427/085138.607908:INFO:naive_connection.cc(273)] Connection 10 to witch.valdikss.org.ru:80
[0427/085141.224345:INFO:naive_connection.cc(273)] Connection 11 to alive.github.com:443
[0427/085145.231536:INFO:naive_connection.cc(273)] Connection 12 to github.com:443
[0427/085154.906494:INFO:naive_connection.cc(273)] Connection 13 to optimizationguide-pa.googleapis.com:443

root@client:/opt/naiveproxy# cat config.json
{
  "listen": "socks://0.0.0.0:1080",
  "proxy": "https://uname:PaSs@server.com",
  "log": ""
}
```

### PR DESCRIPTION
**Pull request by Chilledheart**
Fixes #641.

After this patch, run naive --disable-features=PostQuantumKyber

### CODE REVIEW

**Comment by Chilledheart** [comment]
or add "disable-features": "PostQuantumKyber" line in config json.

**Comment by klzgrad** [comment]
Already available with https://chromeenterprise.google/policies/#PostQuantumKeyAgreementEnabled.

**Comment by Chilledheart** [comment]
And have you tested it?

**Comment by Chilledheart** [comment]
From https://source.chromium.org/search?q=PostQuantumKeyAgreementEnabled&sq=&ss=chromium
It seems naive doesn't contain the policy part of code.

There is no code named chrome_settings.proto which take effect of these google chrome settings.
https://github.com/search?q=repo%3Aklzgrad%2Fnaiveproxy%20chrome_settings.proto&type=code

**Comment by Chilledheart** [comment]
Simply nothing named in a buildtree of naive:
```
HKY@DEFINE7 MINGW64 /d/workspace/naiveproxy (master)
$ find src/out/Release/ -name chrome_settings.proto

HKY@DEFINE7 MINGW64 /d/workspace/naiveproxy (master)
$
```

**Comment by klzgrad** [comment]
> And have you tested it?

No

**Comment by klzgrad** [comment]
I don't want to maintain a pile of garbage code toggling features

**Comment by Chilledheart** [comment]
> I don't want to maintain a pile of garbage code toggling features

you still can hardcode the feature to be off then.

**Comment by Chilledheart** [comment]
> > And have you tested it?
> 
> No

Then, you can test the steps in https://github.com/klzgrad/naiveproxy/pull/642#issuecomment-2094078184 with below code which will print the feature switch's status. But I still wonder if there is a way I can do it in Linux and macOS without config.json and command line.

```
  if (base::FeatureList::IsEnabled(net::features::kPostQuantumKyber)) {
    std::cout << "enabled post quantum kyber curves" << std::endl;
  } else {
    std::cout << "disabled post quantum kyber curves" << std::endl;
  }
```

**Pull request closed without merging**
