### PR TITLE
Add Scoop installation method

### PR DESCRIPTION
**Pull request by kidonng**

### CODE REVIEW

**Comment by klzgrad** [comment]
This is an ad!!

**Comment by kidonng** [comment]
I'm really sorry if you are offended, I didn't intend to promote my repository, just provided an extra installation method. That said, hosting the manifest in a personal repository may not be a good choice at the very beginning.

Can I ask your permission to submit `naiveproxy` manifest to Scoop's official repository to avoid advertising anyone instead?

Thanks for your work and I sincerely apologize.

**Comment by klzgrad** [comment]
Naiveproxy is licensed under BSD 3-Clause. Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the  distribution.
* Neither the name of Google Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

**Comment by kidonng** [comment]
Thanks for your reply, submitted ScoopInstaller/Main#1172. Once the manifest enters into the repository, I will revise the document to use the official source. I would be glad if you can reconsider adding this info to README.

**Comment by kidonng** [comment]
@klzgrad `naiveproxy` is in Scoop's official repository now, could you please reopen this PR or should I create a new one?

**Comment by klzgrad** [comment]
I'll let you know that I respectfully reject the request to endorse your repository.

**Comment by kidonng** [comment]
Like I said above, I have revised the document to use official source instead: https://github.com/klzgrad/naiveproxy/compare/master...kidonng:patch-1

**Pull request closed without merging**
