### PR TITLE
Build fix for MIPS with musl libc

### PR DESCRIPTION
**Pull request by dianlujitao**
sgidefs.h is a glibc header that musl itself doesn't ship, and OpenWRT no
longer additionally provide them after https://git.io/J2D35 , so use the kernel
one instead when not building with glibc.

### CODE REVIEW

**Comment by dianlujitao** [comment]
ref: https://www.openwall.com/lists/musl/2017/02/04/2

**Comment by dianlujitao** [comment]
```
2021-10-02T18:46:31.5461519Z FAILED: obj/base/base/rand_util_posix.o 
2021-10-02T18:46:31.5500181Z ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/base/base/rand_util_posix.o.d -DUSE_SYMBOLIZE -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -D_LIBCPP_HAS_MUSL_LIBC -D__UCLIBC__ -DCR_CLANG_REVISION=\"llvmorg-14-init-1002-gb5e470aa-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -DCR_LIBCXX_REVISION=79a2e924d96e2fc1e4b937c42efd08898fa472d7 -DCR_SYSROOT_HASH=eb577cef43088b7e0540950c74f994267631d4cd -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBASE_IMPLEMENTATION -DOPENSSL_NO_ASM -I../.. -Igen -I../../buildtools/third_party/libc++ -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -ffp-contract=off -fcomplete-member-pointers --target=mipsel-openwrt-linux-musl -march=mipsel -mcpu=mips32r2 -msoft-float -mtune=mips32 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-psabi -Wno-ignored-pragma-optimize -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-inline-asm -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ptr-template-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors -Wshadow -Wglobal-constructors -Wexit-time-destructors -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include --sysroot=../../../../../../staging_dir/toolchain-mipsel_mips32_gcc-11.2.0_musl -fvisibility-inlines-hidden -c ../../base/rand_util_posix.cc -o obj/base/base/rand_util_posix.o
2021-10-02T18:46:31.5514635Z make[3]: *** [Makefile:139: /tmp/tmp.0PW5m3C0hf/build_dir/target-mipsel_mips32_musl/naiveproxy-94.0.4606.61-1/.built] Error 1
2021-10-02T18:46:31.5515562Z In file included from ../../base/rand_util_posix.cc:21:
2021-10-02T18:46:31.5516466Z ../../third_party/lss/linux_syscall_support.h:128:10: fatal error: 'sgidefs.h' file not found
2021-10-02T18:46:31.5517098Z #include <sgidefs.h>
2021-10-02T18:46:31.5517480Z          ^~~~~~~~~~~
2021-10-02T18:46:31.5517854Z 1 error generated.
2021-10-02T18:46:31.5518352Z ninja: build stopped: subcommand failed.
2021-10-02T18:46:31.5519251Z make[3]: Leaving directory '/home/runner/cache/feeds/passwall/naiveproxy'
```

**Comment by klzgrad** [comment]
Which version is this openwrt?

**Comment by dianlujitao** [comment]
> Which version is this openwrt?

snapshot, that tracks the master branch

**Comment by klzgrad** [comment]
Who are affected by this version? Openwrt stable releases 19 and 21 wouldn't be affected by this.

**Comment by dianlujitao** [comment]
> Who are affected by this version? Openwrt stable releases 19 and 21 wouldn't be affected by this.

snapshots are nightly builds and bases of future releases.

**Comment by dianlujitao** [comment]
here's a similar patch of a popular downstream project https://github.com/fw876/helloworld/commit/0b25484890027945936f36375b652b72525b4370

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/commit/4960582500387e0b135e5b30ba9d79ef8a6c98fc

Openwrt builds do not require changes in tcmalloc.

Big-endian MIPS is not supported.

Also, removing concurrency limit of 4 is bad.

**Comment by dianlujitao** [comment]
Yea the tcmalloc changes are just for completeness and not required.

Back to your patch, is `__MUSL__` a thing? That was the first thing that came into my mind, but according to https://wiki.musl-libc.org/faq.html I didn't even give it a try.

**Comment by klzgrad** [comment]
I define __MUSL__ in this build. It is a bug for Musl to introduce theoretical impurity. It is not a bug in practice elsewhere.

**Pull request closed without merging**
