### PR TITLE
Support iOS compile

### PR DESCRIPTION
**Pull request by hw-1**
test success  on iOS 13.7

### CODE REVIEW

**Comment by klzgrad** [comment]
A test case is required to show the built binary works. The test case should work in Github's Mac virtual environment.

That was the question: I know how to build it, but I don't know how to run the built binary to prove it works.

**Comment by hw-1** [comment]
run on jailbreak iOS device

**Comment by Johnshall** [comment]
I will try to get in touch with the author of Shadowrocket. Maybe he could do something to make Naiveproxy working on iOS.

Please hold on for a second.

**Comment by klzgrad** [comment]
iOS build check is added in https://github.com/klzgrad/naiveproxy/blob/master/.github/workflows/build.yml#L450

But no build artifacts are saved, because it's not clear how to verify it works.

These build flags are not necessary: `use_allocator="none" use_allocator_shim=false`.

**Comment by zizifn** [comment]
> I will try to get in touch with the author of Shadowrocket. Maybe he could do something to make Naiveproxy working on iOS.
> 
> Please hold on for a second.

any update on this?

**Comment by Johnshall** [comment]
> > I will try to get in touch with the author of Shadowrocket. Maybe he could do something to make Naiveproxy working on iOS.
> > Please hold on for a second.
> 
> any update on this?

https://github.com/klzgrad/naiveproxy/issues/373#issuecomment-1304582750

**Pull request closed without merging**
